---
title: "R语言课程作业"
author: "邵登科"
date: "2017年6月06日"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

*摘要：*
根据原始数据文件，利用RStudio进行读取及数据处理，采用逐步logistic回归模型进行建模，通过计算测试集合训练集的AUC值，并进行检验，结果表明：此模型具有一定的预测功能。   

# 数据读取及处理
```{r}
library(pROC)
cancer <- read.csv("E:\\rspace\\cancer.csv", stringsAsFactors = FALSE)
cancer <- cancer[ , 1:7]
```
直接读取的原始数据中存在小数点，数据类型为字符型，且存在一定数量的缺失值，需要进一步仅需数据处理。

```{r}
for (i in 1:7) {cancer[cancer[,i]==".",i] <- NA}
for (i in 1:7) {cancer[,i] <- as.numeric(cancer[,i])}
for (i in 1:7) {cancer[is.na(cancer[,i]),i] <- median(na.omit(cancer[,i]))}
for (i in c(1,3,5)) {cancer[,i] <- as.factor(cancer[,i])}
```
将数据中小数点作为缺失值处理，利用中位数代替变量中缺失值。并根据变量属性设置其相关数据类型。

# logistic回归模型
```{r}
set.seed(3)
n = 3000
result.train.auc <- result.test.auc <- c()
for (i in 1:n) {
  cancer.sample    <- sample(1:nrow(cancer), 2/3*nrow(cancer))
  cancer.train     <- cancer[cancer.sample, ]
  cancer.test      <- cancer[-cancer.sample, ]
  
  glm.model  <- glm(Cancer.development ~ ., family=binomial(link = "logit"), data=cancer.train) 
  glm.select <- step(glm.model, direction = "both", trace = 0)

  cancer.test.pred <- predict(glm.select, newdata = cancer.test)
  cancer.test.pred <- exp(cancer.test.pred)/(1+exp(cancer.test.pred))
  result.test.roc <- roc(cancer.test$Cancer.development, cancer.test.pred)
  result.test.auc[i] <- result.test.roc$auc 
  
  cancer.train.pred <- predict(glm.select, newdata = cancer.train)
  cancer.train.pred <- exp(cancer.train.pred)/(1+exp(cancer.train.pred))
  result.train.roc <- roc(cancer.train$Cancer.development, cancer.train.pred)
  result.train.auc[i] <- result.train.roc$auc
}
```


# 计算测试集合训练集的AUC值及检验，绘制相关图像。 
```{r}
mean(result.test.auc)
t.test(result.test.auc, alternative = "greater", mu=0.5)

hist(result.test.auc, freq = F, breaks = 50) 
lines(density(result.test.auc, bw=0.05), col=2, lwd=2)

mean(result.train.auc)
t.test(result.train.auc, alternative = "greater", mu=0.5)

hist(result.train.auc, freq = F, breaks = 50) 
lines(density(result.train.auc, bw=0.05), col=2, lwd=2)
```
