---
title: "R语言课程作业"
author: "邵登科"
date: "2017年6月06日"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 一、数据读取及处理
```{r}
library(pROC)
cancer <- read.csv("E:\\rspace\\cancer.csv", stringsAsFactors = FALSE)
fix(cancer)
str(cancer)
cancer <- cancer[ , 1:7]
```

```{r}
# 去掉小数点
cancer[cancer[,1]==".", 1] <- NA
cancer[cancer[,2]==".", 2] <- NA
cancer[cancer[,3]==".", 3] <- NA
cancer[cancer[,4]==".", 4] <- NA
cancer[cancer[,5]==".", 5] <- NA
cancer[cancer[,6]==".", 6] <- NA
cancer[cancer[,7]==".", 7] <- NA
# 转为数值型
cancer <- sapply(cancer, as.numeric)
cancer <- as.data.frame(cancer)
# 剔除缺失值
cancer <- na.omit(cancer)
# 转为因子型
cancer[,1] <- as.factor(cancer[,1])
cancer[,3] <- as.factor(cancer[,3])
cancer[,5] <- as.factor(cancer[,5])
```

# 二、logictic回归模型建立及检验
```{r}
  set.seed(6)
# 设置训练集和测试集：  
  cancer.sample    <- sample(1:nrow(cancer), 3/4*nrow(cancer))
  cancer.train     <- cancer[cancer.sample, ]
  cancer.test      <- cancer[-cancer.sample, ]
# logistic逐步回归模型：
  glm.model        <- glm(Cancer.development ~ ., family=binomial(link = "logit"), data=cancer.train) 
  glm.select       <- step(glm.model, direction = "both", trace = 0)
  summary(glm.select)
# 模型预测结果检验  
  cancer.test.pred <- predict(glm.select, newdata = cancer.test)
  cancer.test.pred <- exp(cancer.test.pred)/(1+exp(cancer.test.pred))
  result.test.roc  <- roc(cancer.test$Cancer.development, cancer.test.pred)
  plot(result.test.roc, print.auc=TRUE, auc.polygon=TRUE, grid=c(0.1, 0.2),
     grid.col=c("green", "red"), max.auc.polygon=TRUE,
     auc.polygon.col="skyblue", print.thres=TRUE)
```
logistic逐步回归逻辑回归结果：
###  log(p/(1-P))=-4.172+0.537*stage1+0.115*age
a.模型F检验结果显著，而常数项和stage1变量T检验结果显著，而age变量的T检验结果不显著。
b.模型的AUC值为0.607，可以认为模型是具有一定的预测功能的。
根据以上分析可知，此模型是可取的，为了进一步检验模型的预测效果，进行重复建模检验。

# 三、重复建模检验
## 1、重复建模
```{r}
set.seed(6)
n = 3000
result.train.auc <- result.test.auc <- c()
for (i in 1:n) {
  cancer.sample    <- sample(1:nrow(cancer), 3/4*nrow(cancer))
  cancer.train     <- cancer[cancer.sample, ]
  cancer.test      <- cancer[-cancer.sample, ]
  glm.model  <- glm(Cancer.development ~ ., family=binomial(link = "logit"), data=cancer.train) 
  glm.select <- step(glm.model, direction = "both", trace = 0)
  cancer.test.pred <- predict(glm.select, newdata = cancer.test)
  cancer.test.pred <- exp(cancer.test.pred)/(1+exp(cancer.test.pred))
  result.test.roc <- roc(cancer.test$Cancer.development, cancer.test.pred)
  result.test.auc[i] <- result.test.roc$auc 
}
```
重复建立模型3000次，计算每个模型的AUC值，从而进一步分析。

## 2、计算测试集的AUC值及检验，绘制相关图像。 
```{r}
# 计算3000个模型AUC的均值，并进行单侧T检验。
mean(result.test.auc)
t.test(result.test.auc, alternative = "greater", mu=0.5)
# 绘制3000个模型AUC的直方图，并画出密度曲线。
hist(result.test.auc, freq = F, breaks = 50) 
lines(density(result.test.auc, bw=0.05), col=2, lwd=2)
```
3000个模型的AUC均值为 0.5688，
通过T检验单侧假设检验，Ho:mu=0.5,H1:mu>0.5.
根据假设检验结果，可以认为拒绝原假设，认为mu大于0.5,即认为模型是可行的。

# 四、结论
```{r}
# 通过计算测试集的AUC值，检验结果表明：此模型是可行的，具有一定的预测功能。
```
