#!/usr/bin/env python  
# -*- coding: utf-8 -*-  
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")
from math import isnan
import os
from math import isnan

os.getcwd()
os.chdir("C:/Users/Administrator.USER-20161208UW/Desktop")

testdata1 = pd.read_csv("testdata_xlsx.csv",engine='python')

temp1 = []
for temp in testdata1['data_whole_flag']:
    temp1.append(str(temp).zfill(95))

testdata1['data_whole_flag'] = temp1

def f(x):x[x.isnull()] = 0;x[x==-9999] = 0;return x

dat = pd.DataFrame(testdata1.iloc[:,4:100],dtype=np.float).apply(f)

dat['id'] = testdata1['锘縤d']

dat['phase_flag'] = testdata1['phase_flag']

dat['data_whole_flag'] = testdata1['data_whole_flag']

def f1(x):x[x == 0] = -99;x[(x > 0) & (x < 198)] = -1;x[(x >= 198) & (x <= 235.4)] = 0;x[x > 235.4] = 1;return x

temp = dat.iloc[:,0:97].apply(f1).iloc[:,0:96]

def f2(x):n = len(x[x==0]); return n
def f3(x):n = len(x[x==-99]); return n
def f4(x):n = len(x[x==1]); return n
def f5(x):n = len(x[x==-1]); return n

dat['oknum'] = temp.apply(f2,axis=1)
dat['nanum'] = temp.apply(f3,axis=1)
dat['upnum'] = temp.apply(f4,axis=1)
dat['lownum'] = temp.apply(f5,axis=1)

dat_ok = dat[dat['oknum']==96]
dat_na = dat[dat['nanum']!=0]
dat_up = dat[dat['upnum']!=0]
dat_low = dat[dat['lownum']!=0]









